### ISSUE TITLE
Implement four arithmetic operation

### ISSUE THREAD

**Issue by junkyn** [junkyn/four-arithmatic-operation#1]
### Description
Implement four arithmetic operations

### Tasks
- [ ] Implement Add function
- [ ] Implement Subtract function
- [ ] Implement Divide function
- [ ] Implement Multiply function
